services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb  # Isso aponta para o nome do serviço MongoDB
      ME_CONFIG_BASICAUTH_USERNAME: admin  # Adicionando a autenticação básica
      ME_CONFIG_BASICAUTH_PASSWORD: admin123  # Definindo a senha de autenticação básica
    depends_on:
      - mongodb  # Garante que o Mongo Express só inicie depois do MongoDB

volumes:
  mongodata:

# docker-compose -f mongo-compose.yml  up -d
# docker exec -it mongodb-container mongosh -u admin -p admin123
# use admin
# OUTROS COMANDOS:
# docker-compose -f mongo-compose.yml  down -v
# docker ps
# docker exec -it mongodb-container bash
# docker-compose -f mongo-compose.yml logs mongo
# docker-compose -f mongo-compose.yml logs mongo-express